# Generated by Django 4.1.7 on 2023-02-15 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "column_separator",
                    models.CharField(
                        choices=[
                            (",", "Comma"),
                            (";", "Semicolon"),
                            ("\t", "Tab"),
                            ("|", "Pipe"),
                            (":", "Colon"),
                            (" ", "Space"),
                            ("~", "Tilde"),
                            ("/", "Forward slash"),
                        ],
                        default=",",
                        max_length=1,
                    ),
                ),
                (
                    "string_character",
                    models.CharField(
                        choices=[
                            ("'", "Single Quotes"),
                            ('"', "Double Quotes"),
                            ("`", "Backtick"),
                            ("|", "Pipe"),
                            ("#", "Hash"),
                            ("@", "At"),
                        ],
                        default="'",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("full_name", "Full Name"),
                            ("job", "Job"),
                            ("email", "Email"),
                            ("domain_name", "Domain Name"),
                            ("phone_number", "Phone Number"),
                            ("company_name", "Company Name"),
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("address", "Address"),
                            ("date", "Date"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("sentence_count", models.PositiveIntegerField(blank=True, null=True)),
                ("min_value", models.IntegerField(blank=True, null=True)),
                ("max_value", models.IntegerField(blank=True, null=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="generator.schema",
                    ),
                ),
            ],
        ),
    ]
